{
 "title": "Moneybags",
 "tags": [ "financials" ],
 "time": { "from": "now-2y", "to": "now" },
 "panels": [
  { "title": "Financials Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Net Assets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n    transaction_date as \"time\",\n    SUM(amount) as \"Amount\"\n  FROM assets\n  WHERE\n    $__timeFilter(transaction_date)\n  group by transaction_date\n  order by transaction_date"
    }
   ]
  },
  {
   "title": "Net Liquid Assets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n    transaction_date as \"time\",\n    type,\n    amount AS \"Amount\"\n  FROM assets\n  WHERE\n    $__timeFilter(transaction_date)\n    AND type IN ('Bank', 'MMF', 'Investments', 'Bonds') OR type like 'Car:%'\n  group by transaction_date, type, amount\n  order by transaction_date"
    }
   ]
  },
  {
   "title": "Net Illiquid Assets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n    transaction_date as \"time\",\n    type,\n    amount AS \"Amount\"\n  FROM assets\n  WHERE\n    $__timeFilter(transaction_date)\n    AND type IN ('OA', 'SA', 'Medisave', 'SRS', 'House', 'OA CPFIA')\n  group by transaction_date, type, amount\n  order by transaction_date"
    }
   ]
  },
  { "title": "YTD Income/Tax", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Income YTD",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(amount) from incomes where date_part('year', transaction_date) = date_part('year', current_timestamp)"
    }
   ]
  },
  {
   "title": "Total Tax Exclusions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(amount) from\n\n((\n  select\n    date_part('year', current_timestamp) as year,\n    'Employer/Employee CPF contribution' as type,\n    (select sum(amount) from incomes where date_part('year', transaction_date) = date_part('year', current_timestamp) and type like 'CPF%') as amount\n)\nunion\n(\n  select \n    year, type, amount\n  from tax_exclusions\n  where \n    year = date_part('year', current_timestamp)\n))"
    }
   ]
  },
  {
   "title": "Taxable Income",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  (\n    select\n      sum(amount)\n    from\n      incomes\n    where\n      date_part('year', transaction_date) = date_part('year', current_timestamp)\n  ) - sum(amount)\nfrom\n  (\n    (\n      select\n        date_part('year', current_timestamp) as year,\n        'Employer/Employee CPF contribution' as type,\n        (\n          select\n            sum(amount)\n          from\n            incomes\n          where\n            date_part('year', transaction_date) = date_part('year', current_timestamp)\n            and type like 'CPF%'\n        ) as amount\n    )\n    union\n    (\n      select\n        year,\n        type,\n        amount\n      from\n        tax_exclusions\n      where\n        year = date_part('year', current_timestamp)\n    )\n  )"
    }
   ]
  },
  {
   "title": "Tax",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with taxable_income as (\n  select\n    (\n      select\n        sum(amount)\n      from\n        incomes\n      where\n        date_part('year', transaction_date) = date_part('year', current_timestamp)\n    ) - sum(amount) as amount\n  from\n    (\n      (\n        select\n          date_part('year', current_timestamp) as year,\n          'Employer/Employee CPF contribution' as type,\n          (\n            select\n              sum(amount)\n            from\n              incomes\n            where\n              date_part('year', transaction_date) = date_part('year', current_timestamp)\n              and type like 'CPF%'\n          ) as amount\n      )\n      union\n      (\n        select\n          year,\n          type,\n          amount\n        from\n          tax_exclusions\n        where\n          year = date_part('year', current_timestamp)\n      )\n    ) as amount\n)\nselect\n  case\n    when amount >= 1000000 then (amount - 1000000) * 0.24 + 199150\n    when amount >= 500000 then (amount - 500000) * 0.23 + 84150\n    when amount >= 320000 then (amount - 320000) * 0.22 + 44550\n    when amount >= 280000 then (amount - 280000) * 0.20 + 36550\n    when amount >= 240000 then (amount - 240000) * 0.195 + 28750\n    when amount >= 200000 then (amount - 200000) * 0.19 + 21150\n    when amount >= 160000 then (amount - 160000) * 0.18 + 13950\n    when amount >= 120000 then (amount - 120000) * 0.15 + 7950\n    when amount >= 80000 then (amount - 80000) * 0.115 + 3350\n    when amount >= 40000 then (amount - 40000) * 0.07 + 550\n    when amount >= 30000 then (amount - 30000) * 0.035 + 200\n    when amount >= 20000 then (amount - 20000) * 0.02\n    else 0\n  end\nfrom\n  taxable_income\n"
    }
   ]
  },
  {
   "title": "Tax Exclusions",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "(\n  select\n    date_part('year', current_timestamp) as year,\n    'Employer/Employee CPF contribution' as type,\n    (select sum(amount) from incomes where date_part('year', transaction_date) = date_part('year', current_timestamp) and type like 'CPF%') as amount\n)\nunion\n(\n  select \n    year, type, amount\n  from tax_exclusions\n  where \n    year = date_part('year', current_timestamp)\n)"
    }
   ]
  },
  { "title": "Inflow/Outflow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Salary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n    transaction_date as \"time\",\n    type,\n    amount AS \"Amount\"\n  FROM incomes\n  WHERE\n    $__timeFilter(transaction_date)\n  group by transaction_date, type, amount\n  order by transaction_date"
    }
   ]
  },
  {
   "title": "Expenses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "WITH cc as (\n    SELECT\n      transaction_date as \"transaction_date\",\n      sum(amount) as \"amount\"\n    FROM\n      expenses\n    WHERE\n      $__timeFilter(transaction_date)\n      AND type in ('Credit Card', 'Reimbursement')\n    group by transaction_date\n    order by transaction_date\n  )\n  SELECT\n      transaction_date as \"time\",\n      type,\n      amount AS \"Amount\"\n  FROM expenses\n  WHERE\n      $__timeFilter(transaction_date)\n      AND type not in ('Credit Card', 'Reimbursement')\n      AND type not like 'Special:%'\n  UNION select transaction_date as \"time\", 'Credit Card' as type, amount from cc\n  group by transaction_date, type, amount\n  order by time"
    }
   ]
  },
  {
   "title": "Savings Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "WITH expenditure AS (\n  select date_trunc('month', transaction_date) as time, sum(amount) as Amount from expenses where $__timeFilter(transaction_date) and type not like 'Special:%' group by time\n),\nincome as (\n  select date_trunc('month', transaction_date) as time, sum(amount) as Amount from incomes where $__timeFilter(transaction_date) and type in ('Base', 'Base Bonus') group by time\n)\nSELECT\n  expenditure.time + interval '1 month' - interval '1 day' AS \"time\",\n  CASE \n    WHEN income.amount != 0 then (1 - (expenditure.amount / income.amount)) \n    ELSE 0\n  END as \"Savings Rate\"\nFROM expenditure inner join income on income.time = expenditure.time\nWHERE $__timeFilter(expenditure.time)\nORDER BY expenditure.time;"
    }
   ]
  },
  {
   "title": "Special Expenses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n      transaction_date as \"time\",\n      type,\n      amount AS \"Amount\"\n  FROM expenses\n  WHERE\n      $__timeFilter(transaction_date)\n      AND type like 'Special:%'\n  group by transaction_date, type, amount\n  order by time"
    }
   ]
  },
  {
   "title": "Shared Expenses (2 people)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n      expense_date as \"time\",\n      sum(amount) AS \"Amount\"\n  FROM shared_expense\n  WHERE\n      $__timeFilter(expense_date)\n      AND type not like 'Special:%'\n  group by expense_date\n  order by time"
    }
   ]
  },
  {
   "title": "Special Shared Expenses (2 people)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n      expense_date as \"time\",\n      sum(amount) AS \"Amount\"\n  FROM shared_expense\n  WHERE\n      $__timeFilter(expense_date)\n      AND type like 'Special:%'\n  group by expense_date\n  order by time"
    }
   ]
  },
  { "title": "Car", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Car NAV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n    transaction_date as \"time\",\n    type,\n    amount AS \"Amount\"\n  FROM assets\n  WHERE\n    $__timeFilter(transaction_date)\n    AND type like 'Car:%'\n  group by transaction_date, type, amount\n  order by transaction_date"
    }
   ]
  },
  {
   "title": "Car Payment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n    date as \"time\",\n    name as \"name\",\n    amount_paid as \"Amount Paid\",\n    amount_left+amount_paid as \"Total\"\nFROM car_loans\nWHERE\n    $__timeFilter(date)\ngroup by date, name, amount_paid, amount_left+amount_paid\norder by time"
    }
   ]
  },
  { "title": "Mortgage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Mortgage Payment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n    date as \"time\",\n    interest_paid as \"Interest Paid\",\n    principal_paid AS \"Principal Paid\"\nFROM mortgage\nWHERE\n    $__timeFilter(date)\ngroup by date, interest_paid, principal_paid\norder by time"
    }
   ]
  },
  {
   "title": "Mortgage Summary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n    date as \"time\",\n    total_interest_left as \"Interest Left\",\n    total_principal_left AS \"Principal Left\"\nFROM mortgage\nWHERE\n    $__timeFilter(date)\ngroup by date, total_interest_left, total_principal_left\norder by time"
    }
   ]
  },
  {
   "title": "Mortgage Serviced",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n    date as \"time\",\n    total_interest_paid as \"Total Interest Paid\",\n    total_principal_paid AS \"Total Principal Paid\"\nFROM mortgage\nWHERE\n    $__timeFilter(date)\ngroup by date, total_interest_paid, total_principal_paid\norder by time"
    }
   ]
  },
  { "title": "Financial Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Emergency Funds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "Months" } },
   "targets": [
    {
     "rawSql": "WITH avg_exp AS (\n    select expense_date + INTERVAL '1 day' as \"expense_date\", amount from average_expenditures\n),\nbank AS (\n    select transaction_date, sum(amount) as amount from assets where type in ('Bank', 'Bonds') group by transaction_date\n)\nselect\n    a.expense_date as \"time\",\n    b.amount / a.amount as \"months\"\nfrom\n    avg_exp a inner join bank b on a.expense_date = b.transaction_date\nWHERE $__timeFilter(a.expense_date)\nORDER BY a.expense_date;"
    }
   ]
  },
  {
   "title": "Runway Based on 70% Equity + Bank + Bonds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "Months" } },
   "targets": [
    {
     "rawSql": "WITH avg_exp AS (\n    select expense_date + INTERVAL '1 day' as \"expense_date\", amount from average_expenditures\n),\nbank AS (\n    select transaction_date, sum(amount) as amount from assets where type in ('Bank', 'Bonds') group by transaction_date\n),\nequity AS (\n    select transaction_date, amount from assets where type = 'Investments'\n)\nselect\n    a.expense_date as \"time\",\n    (b.amount + (c.amount * 0.7)) / a.amount as \"months\"\nfrom\n    avg_exp a inner join bank b on a.expense_date = b.transaction_date\n    inner join equity c on a.expense_date = c.transaction_date\nWHERE $__timeFilter(a.expense_date)\nORDER BY a.expense_date;"
    }
   ]
  },
  {
   "title": "Financial Independence Quotient (4% Withdrawal)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "WITH avg_exp AS (\n    select expense_date + INTERVAL '1 day' as \"expense_date\", amount from average_expenditures\n),\nequity AS (\n    select transaction_date, sum(amount) as amount from assets where type in ('Investments', 'Bonds') group by transaction_date\n)\nselect\n    a.expense_date as \"time\",\n    (0.04 * c.amount) / (a.amount * 12) as \"quotient\"\nfrom\n    avg_exp a inner join equity c on a.expense_date = c.transaction_date\nWHERE $__timeFilter(a.expense_date)\nORDER BY a.expense_date;"
    }
   ]
  },
  { "title": "Current Investments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Current Portfolio",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 62 },
   "targets": [
    {
     "rawSql": "\n    WITH total AS (\n      SELECT\n        sum(nav) AS total\n      FROM portfolios\n      WHERE\n        trade_date=DATE_TRUNC('day', CURRENT_TIMESTAMP - INTERVAL '1 day') + INTERVAL '8 hours'\n    ),\n    stock as (\n      SELECT\n        symbol,\n        price\n      FROM stocks\n      WHERE\n        trade_date = (\n          SELECT\n            trade_date\n          FROM stocks\n          ORDER BY trade_date desc\n          LIMIT 1\n        )\n    )\n    SELECT\n      trade_date as time,\n      stock.symbol as symbol,\n      stock.price as current_price,\n      quantity as quantity,\n      sum(nav) as nav,\n      sum(principal) as principal,\n      (sum(nav) - sum(principal)) / sum(principal) as returns,\n      sum(nav)/total.total as percentage\n    FROM portfolios inner join stock on portfolios.symbol = stock.symbol, total\n    WHERE\n      trade_date=DATE_TRUNC('day', CURRENT_TIMESTAMP - INTERVAL '1 day') + INTERVAL '8 hours'\n    group by trade_date, stock.symbol, total.total, quantity, stock.price\n    order by trade_date"
    }
   ]
  },
  {
   "title": "Principal",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    trade_date as \"time\",\n    sum(principal) as \"principal\"\n  FROM portfolios\n  WHERE\n    trade_date=DATE_TRUNC('day', CURRENT_TIMESTAMP - INTERVAL '1 day') + INTERVAL '8 hours'\n  group by trade_date\n  order by trade_date"
    }
   ]
  },
  {
   "title": "NAV",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    trade_date as \"time\",\n    sum(nav) as \"nav\"\n  FROM portfolios\n  WHERE\n    trade_date=DATE_TRUNC('day', CURRENT_TIMESTAMP - INTERVAL '1 day') + INTERVAL '8 hours'\n  group by trade_date\n  order by trade_date"
    }
   ]
  },
  {
   "title": "Unrlz",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    trade_date as \"time\",\n    (sum(nav) - sum(principal)) as \"unrlz\"\n  FROM portfolios\n  WHERE\n    trade_date=DATE_TRUNC('day', CURRENT_TIMESTAMP - INTERVAL '1 day') + INTERVAL '8 hours'\n  group by trade_date\n  order by trade_date"
    }
   ]
  },
  {
   "title": "Simple Returns",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    trade_date as \"time\",\n    (sum(nav) - sum(principal)) / sum(principal) as \"returns\"\n  FROM portfolios\n  WHERE\n    trade_date=DATE_TRUNC('day', CURRENT_TIMESTAMP - INTERVAL '1 day') + INTERVAL '8 hours'\n  group by trade_date\n  order by trade_date"
    }
   ]
  },
  {
   "title": "Portfolio",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n      trade_date as \"time\",\n      symbol,\n      sum(nav) as \"nav\"\n    FROM portfolios\n    WHERE\n      trade_date=DATE_TRUNC('day', CURRENT_TIMESTAMP - INTERVAL '1 day') + INTERVAL '8 hours'\n    group by trade_date, symbol\n    order by trade_date"
    }
   ]
  },
  {
   "title": "Trades",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 70 },
   "targets": [
    {
     "rawSql": "with latest_price as (\r\n  select trade_date, symbol, price from stocks where trade_date = (select max(trade_date) from stocks)\r\n)\r\nselect \r\n  TO_CHAR(trades.date_purchased, 'YYYY/MM/DD') as Date, \r\n  trades.trade_type as Type, trades.symbol as Symbol, \r\n  trades.price_each As Price, \r\n  trades.quantity as Quantity, \r\n  trades.price_each * trades.quantity as Cost,\r\n  (latest_price.price - trades.price_each) / trades.price_each * 100 as Gain\r\nfrom trades INNER JOIN latest_price on latest_price.symbol = trades.symbol order by trades.date_purchased desc;"
    }
   ]
  },
  {
   "title": "Investment Historical Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 }
  },
  {
   "title": "Portfolio Simple Returns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n    trade_date as \"time\",\n    (sum(nav) - sum(principal)) / sum(principal) as \"returns\"\n  FROM portfolios\n  WHERE\n    $__timeFilter(trade_date)\n  group by trade_date\n  order by trade_date"
    }
   ]
  },
  {
   "title": "Portfolio NAV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n    trade_date as \"time\",\n    sum(nav) as \"nav\",\n    sum(principal) as \"principal\"\n  FROM portfolios\n  WHERE\n    $__timeFilter(trade_date)\n  group by trade_date\n  order by trade_date"
    }
   ]
  },
  {
   "title": "Simple Returns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n    trade_date as \"time\",\n    symbol,\n    (sum(nav) - sum(principal))/ sum(principal) as \"returns\"\n  FROM portfolios\n  WHERE\n    $__timeFilter(trade_date)\n  group by trade_date, symbol\n  order by trade_date"
    }
   ]
  },
  {
   "title": "NAV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n    trade_date as \"time\",\n    symbol,\n    sum(nav) as \"nav\"\n  FROM portfolios\n  WHERE\n    $__timeFilter(trade_date)\n  group by trade_date, symbol\n  order by trade_date"
    }
   ]
  }
 ]
}