// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.3
// source: moneybags.proto

package configpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PostgresDb       *PostgresDB            `protobuf:"bytes,1,opt,name=postgres_db,json=postgresDb,proto3" json:"postgres_db,omitempty"`
	TelegramConfig   *TelegramConfig        `protobuf:"bytes,2,opt,name=telegram_config,json=telegramConfig,proto3" json:"telegram_config,omitempty"`
	FinancialsData   *FinancialsData        `protobuf:"bytes,3,opt,name=financials_data,json=financialsData,proto3" json:"financials_data,omitempty"`
	FinancialsConfig *FinancialsConfig      `protobuf:"bytes,4,opt,name=financials_config,json=financialsConfig,proto3" json:"financials_config,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_moneybags_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_moneybags_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_moneybags_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetPostgresDb() *PostgresDB {
	if x != nil {
		return x.PostgresDb
	}
	return nil
}

func (x *Config) GetTelegramConfig() *TelegramConfig {
	if x != nil {
		return x.TelegramConfig
	}
	return nil
}

func (x *Config) GetFinancialsData() *FinancialsData {
	if x != nil {
		return x.FinancialsData
	}
	return nil
}

func (x *Config) GetFinancialsConfig() *FinancialsConfig {
	if x != nil {
		return x.FinancialsConfig
	}
	return nil
}

type PostgresDB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	DbName        string                 `protobuf:"bytes,4,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	Port          uint32                 `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostgresDB) Reset() {
	*x = PostgresDB{}
	mi := &file_moneybags_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostgresDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostgresDB) ProtoMessage() {}

func (x *PostgresDB) ProtoReflect() protoreflect.Message {
	mi := &file_moneybags_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostgresDB.ProtoReflect.Descriptor instead.
func (*PostgresDB) Descriptor() ([]byte, []int) {
	return file_moneybags_proto_rawDescGZIP(), []int{1}
}

func (x *PostgresDB) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *PostgresDB) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *PostgresDB) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *PostgresDB) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *PostgresDB) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type TelegramConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Debug         bool                   `protobuf:"varint,2,opt,name=debug,proto3" json:"debug,omitempty"`
	AllowedUser   string                 `protobuf:"bytes,3,opt,name=allowed_user,json=allowedUser,proto3" json:"allowed_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelegramConfig) Reset() {
	*x = TelegramConfig{}
	mi := &file_moneybags_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramConfig) ProtoMessage() {}

func (x *TelegramConfig) ProtoReflect() protoreflect.Message {
	mi := &file_moneybags_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramConfig.ProtoReflect.Descriptor instead.
func (*TelegramConfig) Descriptor() ([]byte, []int) {
	return file_moneybags_proto_rawDescGZIP(), []int{2}
}

func (x *TelegramConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *TelegramConfig) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

func (x *TelegramConfig) GetAllowedUser() string {
	if x != nil {
		return x.AllowedUser
	}
	return ""
}

type FinancialsData struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	AssetsCsvFilepath         string                 `protobuf:"bytes,1,opt,name=assets_csv_filepath,json=assetsCsvFilepath,proto3" json:"assets_csv_filepath,omitempty"`
	ExpensesCsvFilepath       string                 `protobuf:"bytes,2,opt,name=expenses_csv_filepath,json=expensesCsvFilepath,proto3" json:"expenses_csv_filepath,omitempty"`
	IncomeCsvFilepath         string                 `protobuf:"bytes,3,opt,name=income_csv_filepath,json=incomeCsvFilepath,proto3" json:"income_csv_filepath,omitempty"`
	SharedExpensesCsvFilepath string                 `protobuf:"bytes,4,opt,name=shared_expenses_csv_filepath,json=sharedExpensesCsvFilepath,proto3" json:"shared_expenses_csv_filepath,omitempty"`
	TradesCsvFilepath         string                 `protobuf:"bytes,5,opt,name=trades_csv_filepath,json=tradesCsvFilepath,proto3" json:"trades_csv_filepath,omitempty"`
	MortgageYamlFilepath      string                 `protobuf:"bytes,6,opt,name=mortgage_yaml_filepath,json=mortgageYamlFilepath,proto3" json:"mortgage_yaml_filepath,omitempty"`
	CarYamlFilepath           string                 `protobuf:"bytes,7,opt,name=car_yaml_filepath,json=carYamlFilepath,proto3" json:"car_yaml_filepath,omitempty"`
	TaxExclusionsCsvFilepath  string                 `protobuf:"bytes,8,opt,name=tax_exclusions_csv_filepath,json=taxExclusionsCsvFilepath,proto3" json:"tax_exclusions_csv_filepath,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *FinancialsData) Reset() {
	*x = FinancialsData{}
	mi := &file_moneybags_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinancialsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinancialsData) ProtoMessage() {}

func (x *FinancialsData) ProtoReflect() protoreflect.Message {
	mi := &file_moneybags_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinancialsData.ProtoReflect.Descriptor instead.
func (*FinancialsData) Descriptor() ([]byte, []int) {
	return file_moneybags_proto_rawDescGZIP(), []int{3}
}

func (x *FinancialsData) GetAssetsCsvFilepath() string {
	if x != nil {
		return x.AssetsCsvFilepath
	}
	return ""
}

func (x *FinancialsData) GetExpensesCsvFilepath() string {
	if x != nil {
		return x.ExpensesCsvFilepath
	}
	return ""
}

func (x *FinancialsData) GetIncomeCsvFilepath() string {
	if x != nil {
		return x.IncomeCsvFilepath
	}
	return ""
}

func (x *FinancialsData) GetSharedExpensesCsvFilepath() string {
	if x != nil {
		return x.SharedExpensesCsvFilepath
	}
	return ""
}

func (x *FinancialsData) GetTradesCsvFilepath() string {
	if x != nil {
		return x.TradesCsvFilepath
	}
	return ""
}

func (x *FinancialsData) GetMortgageYamlFilepath() string {
	if x != nil {
		return x.MortgageYamlFilepath
	}
	return ""
}

func (x *FinancialsData) GetCarYamlFilepath() string {
	if x != nil {
		return x.CarYamlFilepath
	}
	return ""
}

func (x *FinancialsData) GetTaxExclusionsCsvFilepath() string {
	if x != nil {
		return x.TaxExclusionsCsvFilepath
	}
	return ""
}

type FinancialsConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RunIntervalInHours int32                  `protobuf:"varint,1,opt,name=run_interval_in_hours,json=runIntervalInHours,proto3" json:"run_interval_in_hours,omitempty"`
	AlphavantageApiKey string                 `protobuf:"bytes,2,opt,name=alphavantage_api_key,json=alphavantageApiKey,proto3" json:"alphavantage_api_key,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FinancialsConfig) Reset() {
	*x = FinancialsConfig{}
	mi := &file_moneybags_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinancialsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinancialsConfig) ProtoMessage() {}

func (x *FinancialsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_moneybags_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinancialsConfig.ProtoReflect.Descriptor instead.
func (*FinancialsConfig) Descriptor() ([]byte, []int) {
	return file_moneybags_proto_rawDescGZIP(), []int{4}
}

func (x *FinancialsConfig) GetRunIntervalInHours() int32 {
	if x != nil {
		return x.RunIntervalInHours
	}
	return 0
}

func (x *FinancialsConfig) GetAlphavantageApiKey() string {
	if x != nil {
		return x.AlphavantageApiKey
	}
	return ""
}

var File_moneybags_proto protoreflect.FileDescriptor

const file_moneybags_proto_rawDesc = "" +
	"\n" +
	"\x0fmoneybags.proto\x12\x06config\"\x86\x02\n" +
	"\x06Config\x123\n" +
	"\vpostgres_db\x18\x01 \x01(\v2\x12.config.PostgresDBR\n" +
	"postgresDb\x12?\n" +
	"\x0ftelegram_config\x18\x02 \x01(\v2\x16.config.TelegramConfigR\x0etelegramConfig\x12?\n" +
	"\x0ffinancials_data\x18\x03 \x01(\v2\x16.config.FinancialsDataR\x0efinancialsData\x12E\n" +
	"\x11financials_config\x18\x04 \x01(\v2\x18.config.FinancialsConfigR\x10financialsConfig\"}\n" +
	"\n" +
	"PostgresDB\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x17\n" +
	"\adb_name\x18\x04 \x01(\tR\x06dbName\x12\x12\n" +
	"\x04port\x18\x05 \x01(\rR\x04port\"b\n" +
	"\x0eTelegramConfig\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x14\n" +
	"\x05debug\x18\x02 \x01(\bR\x05debug\x12!\n" +
	"\fallowed_user\x18\x03 \x01(\tR\vallowedUser\"\xb6\x03\n" +
	"\x0eFinancialsData\x12.\n" +
	"\x13assets_csv_filepath\x18\x01 \x01(\tR\x11assetsCsvFilepath\x122\n" +
	"\x15expenses_csv_filepath\x18\x02 \x01(\tR\x13expensesCsvFilepath\x12.\n" +
	"\x13income_csv_filepath\x18\x03 \x01(\tR\x11incomeCsvFilepath\x12?\n" +
	"\x1cshared_expenses_csv_filepath\x18\x04 \x01(\tR\x19sharedExpensesCsvFilepath\x12.\n" +
	"\x13trades_csv_filepath\x18\x05 \x01(\tR\x11tradesCsvFilepath\x124\n" +
	"\x16mortgage_yaml_filepath\x18\x06 \x01(\tR\x14mortgageYamlFilepath\x12*\n" +
	"\x11car_yaml_filepath\x18\a \x01(\tR\x0fcarYamlFilepath\x12=\n" +
	"\x1btax_exclusions_csv_filepath\x18\b \x01(\tR\x18taxExclusionsCsvFilepath\"w\n" +
	"\x10FinancialsConfig\x121\n" +
	"\x15run_interval_in_hours\x18\x01 \x01(\x05R\x12runIntervalInHours\x120\n" +
	"\x14alphavantage_api_key\x18\x02 \x01(\tR\x12alphavantageApiKeyB\x11Z\x0f./pbgo/configpbb\x06proto3"

var (
	file_moneybags_proto_rawDescOnce sync.Once
	file_moneybags_proto_rawDescData []byte
)

func file_moneybags_proto_rawDescGZIP() []byte {
	file_moneybags_proto_rawDescOnce.Do(func() {
		file_moneybags_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moneybags_proto_rawDesc), len(file_moneybags_proto_rawDesc)))
	})
	return file_moneybags_proto_rawDescData
}

var file_moneybags_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_moneybags_proto_goTypes = []any{
	(*Config)(nil),           // 0: config.Config
	(*PostgresDB)(nil),       // 1: config.PostgresDB
	(*TelegramConfig)(nil),   // 2: config.TelegramConfig
	(*FinancialsData)(nil),   // 3: config.FinancialsData
	(*FinancialsConfig)(nil), // 4: config.FinancialsConfig
}
var file_moneybags_proto_depIdxs = []int32{
	1, // 0: config.Config.postgres_db:type_name -> config.PostgresDB
	2, // 1: config.Config.telegram_config:type_name -> config.TelegramConfig
	3, // 2: config.Config.financials_data:type_name -> config.FinancialsData
	4, // 3: config.Config.financials_config:type_name -> config.FinancialsConfig
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_moneybags_proto_init() }
func file_moneybags_proto_init() {
	if File_moneybags_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moneybags_proto_rawDesc), len(file_moneybags_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_moneybags_proto_goTypes,
		DependencyIndexes: file_moneybags_proto_depIdxs,
		MessageInfos:      file_moneybags_proto_msgTypes,
	}.Build()
	File_moneybags_proto = out.File
	file_moneybags_proto_goTypes = nil
	file_moneybags_proto_depIdxs = nil
}
