apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ include "moneybags.fullname" . }}-postgres
  name: {{ include "moneybags.fullname" . }}-postgres
spec:
  selector:
    name: {{ include "moneybags.fullname" . }}-postgres
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
