{{- if .Values.mcp.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "moneybags.fullname" . }}
  labels:
    {{- include "moneybags.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "moneybags.selectorLabels" . | nindent 4 }}
  ports:
  - name: mcp
    port: 80
    targetPort: 6000
    protocol: TCP
{{- end }}
