// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: mortgage.proto

package mortgagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MortgageConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mortgages []*Mortgage `protobuf:"bytes,1,rep,name=mortgages,proto3" json:"mortgages,omitempty"`
}

func (x *MortgageConfig) Reset() {
	*x = MortgageConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mortgage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MortgageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MortgageConfig) ProtoMessage() {}

func (x *MortgageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_mortgage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MortgageConfig.ProtoReflect.Descriptor instead.
func (*MortgageConfig) Descriptor() ([]byte, []int) {
	return file_mortgage_proto_rawDescGZIP(), []int{0}
}

func (x *MortgageConfig) GetMortgages() []*Mortgage {
	if x != nil {
		return x.Mortgages
	}
	return nil
}

type Mortgage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total                   float64        `protobuf:"fixed64,1,opt,name=total,proto3" json:"total,omitempty"`
	MortgageFirstPayment    string         `protobuf:"bytes,2,opt,name=mortgage_first_payment,json=mortgageFirstPayment,proto3" json:"mortgage_first_payment,omitempty"`
	MortgageDurationInYears uint32         `protobuf:"varint,3,opt,name=mortgage_duration_in_years,json=mortgageDurationInYears,proto3" json:"mortgage_duration_in_years,omitempty"`
	MortgageEndDate         string         `protobuf:"bytes,4,opt,name=mortgage_end_date,json=mortgageEndDate,proto3" json:"mortgage_end_date,omitempty"`
	InterestRatePercentage  float64        `protobuf:"fixed64,5,opt,name=interest_rate_percentage,json=interestRatePercentage,proto3" json:"interest_rate_percentage,omitempty"`
	Downpayments            []*Downpayment `protobuf:"bytes,6,rep,name=downpayments,proto3" json:"downpayments,omitempty"`
}

func (x *Mortgage) Reset() {
	*x = Mortgage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mortgage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mortgage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mortgage) ProtoMessage() {}

func (x *Mortgage) ProtoReflect() protoreflect.Message {
	mi := &file_mortgage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mortgage.ProtoReflect.Descriptor instead.
func (*Mortgage) Descriptor() ([]byte, []int) {
	return file_mortgage_proto_rawDescGZIP(), []int{1}
}

func (x *Mortgage) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Mortgage) GetMortgageFirstPayment() string {
	if x != nil {
		return x.MortgageFirstPayment
	}
	return ""
}

func (x *Mortgage) GetMortgageDurationInYears() uint32 {
	if x != nil {
		return x.MortgageDurationInYears
	}
	return 0
}

func (x *Mortgage) GetMortgageEndDate() string {
	if x != nil {
		return x.MortgageEndDate
	}
	return ""
}

func (x *Mortgage) GetInterestRatePercentage() float64 {
	if x != nil {
		return x.InterestRatePercentage
	}
	return 0
}

func (x *Mortgage) GetDownpayments() []*Downpayment {
	if x != nil {
		return x.Downpayments
	}
	return nil
}

type Downpayment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date string  `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Sum  float64 `protobuf:"fixed64,2,opt,name=sum,proto3" json:"sum,omitempty"`
}

func (x *Downpayment) Reset() {
	*x = Downpayment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mortgage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Downpayment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Downpayment) ProtoMessage() {}

func (x *Downpayment) ProtoReflect() protoreflect.Message {
	mi := &file_mortgage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Downpayment.ProtoReflect.Descriptor instead.
func (*Downpayment) Descriptor() ([]byte, []int) {
	return file_mortgage_proto_rawDescGZIP(), []int{2}
}

func (x *Downpayment) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Downpayment) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

var File_mortgage_proto protoreflect.FileDescriptor

var file_mortgage_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x6f, 0x72, 0x74, 0x67, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6d, 0x6f, 0x72, 0x74, 0x67, 0x61, 0x67, 0x65, 0x22, 0x42, 0x0a, 0x0e, 0x4d, 0x6f,
	0x72, 0x74, 0x67, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x30, 0x0a, 0x09,
	0x6d, 0x6f, 0x72, 0x74, 0x67, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x6d, 0x6f, 0x72, 0x74, 0x67, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x6f, 0x72, 0x74, 0x67,
	0x61, 0x67, 0x65, 0x52, 0x09, 0x6d, 0x6f, 0x72, 0x74, 0x67, 0x61, 0x67, 0x65, 0x73, 0x22, 0xb4,
	0x02, 0x0a, 0x08, 0x4d, 0x6f, 0x72, 0x74, 0x67, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x34, 0x0a, 0x16, 0x6d, 0x6f, 0x72, 0x74, 0x67, 0x61, 0x67, 0x65, 0x5f, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x14, 0x6d, 0x6f, 0x72, 0x74, 0x67, 0x61, 0x67, 0x65, 0x46, 0x69, 0x72, 0x73, 0x74,
	0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3b, 0x0a, 0x1a, 0x6d, 0x6f, 0x72, 0x74, 0x67,
	0x61, 0x67, 0x65, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x5f,
	0x79, 0x65, 0x61, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x17, 0x6d, 0x6f, 0x72,
	0x74, 0x67, 0x61, 0x67, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x59,
	0x65, 0x61, 0x72, 0x73, 0x12, 0x2a, 0x0a, 0x11, 0x6d, 0x6f, 0x72, 0x74, 0x67, 0x61, 0x67, 0x65,
	0x5f, 0x65, 0x6e, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x6d, 0x6f, 0x72, 0x74, 0x67, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65,
	0x12, 0x38, 0x0a, 0x18, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x5f, 0x72, 0x61, 0x74,
	0x65, 0x5f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x16, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x52, 0x61, 0x74, 0x65,
	0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x12, 0x39, 0x0a, 0x0c, 0x64, 0x6f,
	0x77, 0x6e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x6d, 0x6f, 0x72, 0x74, 0x67, 0x61, 0x67, 0x65, 0x2e, 0x44, 0x6f, 0x77, 0x6e,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0c, 0x64, 0x6f, 0x77, 0x6e, 0x70, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x33, 0x0a, 0x0b, 0x44, 0x6f, 0x77, 0x6e, 0x70, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x75, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x73, 0x75, 0x6d, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f,
	0x70, 0x62, 0x67, 0x6f, 0x2f, 0x6d, 0x6f, 0x72, 0x74, 0x67, 0x61, 0x67, 0x65, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mortgage_proto_rawDescOnce sync.Once
	file_mortgage_proto_rawDescData = file_mortgage_proto_rawDesc
)

func file_mortgage_proto_rawDescGZIP() []byte {
	file_mortgage_proto_rawDescOnce.Do(func() {
		file_mortgage_proto_rawDescData = protoimpl.X.CompressGZIP(file_mortgage_proto_rawDescData)
	})
	return file_mortgage_proto_rawDescData
}

var file_mortgage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mortgage_proto_goTypes = []any{
	(*MortgageConfig)(nil), // 0: mortgage.MortgageConfig
	(*Mortgage)(nil),       // 1: mortgage.Mortgage
	(*Downpayment)(nil),    // 2: mortgage.Downpayment
}
var file_mortgage_proto_depIdxs = []int32{
	1, // 0: mortgage.MortgageConfig.mortgages:type_name -> mortgage.Mortgage
	2, // 1: mortgage.Mortgage.downpayments:type_name -> mortgage.Downpayment
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mortgage_proto_init() }
func file_mortgage_proto_init() {
	if File_mortgage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mortgage_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MortgageConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mortgage_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Mortgage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mortgage_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Downpayment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mortgage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mortgage_proto_goTypes,
		DependencyIndexes: file_mortgage_proto_depIdxs,
		MessageInfos:      file_mortgage_proto_msgTypes,
	}.Build()
	File_mortgage_proto = out.File
	file_mortgage_proto_rawDesc = nil
	file_mortgage_proto_goTypes = nil
	file_mortgage_proto_depIdxs = nil
}
