// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.3
// source: mortgage.proto

package mortgagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MortgageConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mortgages     []*Mortgage            `protobuf:"bytes,1,rep,name=mortgages,proto3" json:"mortgages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MortgageConfig) Reset() {
	*x = MortgageConfig{}
	mi := &file_mortgage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MortgageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MortgageConfig) ProtoMessage() {}

func (x *MortgageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_mortgage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MortgageConfig.ProtoReflect.Descriptor instead.
func (*MortgageConfig) Descriptor() ([]byte, []int) {
	return file_mortgage_proto_rawDescGZIP(), []int{0}
}

func (x *MortgageConfig) GetMortgages() []*Mortgage {
	if x != nil {
		return x.Mortgages
	}
	return nil
}

type Mortgage struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Total                   float64                `protobuf:"fixed64,1,opt,name=total,proto3" json:"total,omitempty"`
	MortgageFirstPayment    string                 `protobuf:"bytes,2,opt,name=mortgage_first_payment,json=mortgageFirstPayment,proto3" json:"mortgage_first_payment,omitempty"`
	MortgageDurationInYears uint32                 `protobuf:"varint,3,opt,name=mortgage_duration_in_years,json=mortgageDurationInYears,proto3" json:"mortgage_duration_in_years,omitempty"`
	MortgageEndDate         string                 `protobuf:"bytes,4,opt,name=mortgage_end_date,json=mortgageEndDate,proto3" json:"mortgage_end_date,omitempty"`
	InterestRatePercentage  float64                `protobuf:"fixed64,5,opt,name=interest_rate_percentage,json=interestRatePercentage,proto3" json:"interest_rate_percentage,omitempty"`
	Downpayments            []*Downpayment         `protobuf:"bytes,6,rep,name=downpayments,proto3" json:"downpayments,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Mortgage) Reset() {
	*x = Mortgage{}
	mi := &file_mortgage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mortgage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mortgage) ProtoMessage() {}

func (x *Mortgage) ProtoReflect() protoreflect.Message {
	mi := &file_mortgage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mortgage.ProtoReflect.Descriptor instead.
func (*Mortgage) Descriptor() ([]byte, []int) {
	return file_mortgage_proto_rawDescGZIP(), []int{1}
}

func (x *Mortgage) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Mortgage) GetMortgageFirstPayment() string {
	if x != nil {
		return x.MortgageFirstPayment
	}
	return ""
}

func (x *Mortgage) GetMortgageDurationInYears() uint32 {
	if x != nil {
		return x.MortgageDurationInYears
	}
	return 0
}

func (x *Mortgage) GetMortgageEndDate() string {
	if x != nil {
		return x.MortgageEndDate
	}
	return ""
}

func (x *Mortgage) GetInterestRatePercentage() float64 {
	if x != nil {
		return x.InterestRatePercentage
	}
	return 0
}

func (x *Mortgage) GetDownpayments() []*Downpayment {
	if x != nil {
		return x.Downpayments
	}
	return nil
}

type Downpayment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Sum           float64                `protobuf:"fixed64,2,opt,name=sum,proto3" json:"sum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Downpayment) Reset() {
	*x = Downpayment{}
	mi := &file_mortgage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Downpayment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Downpayment) ProtoMessage() {}

func (x *Downpayment) ProtoReflect() protoreflect.Message {
	mi := &file_mortgage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Downpayment.ProtoReflect.Descriptor instead.
func (*Downpayment) Descriptor() ([]byte, []int) {
	return file_mortgage_proto_rawDescGZIP(), []int{2}
}

func (x *Downpayment) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Downpayment) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

var File_mortgage_proto protoreflect.FileDescriptor

const file_mortgage_proto_rawDesc = "" +
	"\n" +
	"\x0emortgage.proto\x12\bmortgage\"B\n" +
	"\x0eMortgageConfig\x120\n" +
	"\tmortgages\x18\x01 \x03(\v2\x12.mortgage.MortgageR\tmortgages\"\xb4\x02\n" +
	"\bMortgage\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x01R\x05total\x124\n" +
	"\x16mortgage_first_payment\x18\x02 \x01(\tR\x14mortgageFirstPayment\x12;\n" +
	"\x1amortgage_duration_in_years\x18\x03 \x01(\rR\x17mortgageDurationInYears\x12*\n" +
	"\x11mortgage_end_date\x18\x04 \x01(\tR\x0fmortgageEndDate\x128\n" +
	"\x18interest_rate_percentage\x18\x05 \x01(\x01R\x16interestRatePercentage\x129\n" +
	"\fdownpayments\x18\x06 \x03(\v2\x15.mortgage.DownpaymentR\fdownpayments\"3\n" +
	"\vDownpayment\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x10\n" +
	"\x03sum\x18\x02 \x01(\x01R\x03sumB\x13Z\x11./pbgo/mortgagepbb\x06proto3"

var (
	file_mortgage_proto_rawDescOnce sync.Once
	file_mortgage_proto_rawDescData []byte
)

func file_mortgage_proto_rawDescGZIP() []byte {
	file_mortgage_proto_rawDescOnce.Do(func() {
		file_mortgage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mortgage_proto_rawDesc), len(file_mortgage_proto_rawDesc)))
	})
	return file_mortgage_proto_rawDescData
}

var file_mortgage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mortgage_proto_goTypes = []any{
	(*MortgageConfig)(nil), // 0: mortgage.MortgageConfig
	(*Mortgage)(nil),       // 1: mortgage.Mortgage
	(*Downpayment)(nil),    // 2: mortgage.Downpayment
}
var file_mortgage_proto_depIdxs = []int32{
	1, // 0: mortgage.MortgageConfig.mortgages:type_name -> mortgage.Mortgage
	2, // 1: mortgage.Mortgage.downpayments:type_name -> mortgage.Downpayment
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mortgage_proto_init() }
func file_mortgage_proto_init() {
	if File_mortgage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mortgage_proto_rawDesc), len(file_mortgage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mortgage_proto_goTypes,
		DependencyIndexes: file_mortgage_proto_depIdxs,
		MessageInfos:      file_mortgage_proto_msgTypes,
	}.Build()
	File_mortgage_proto = out.File
	file_mortgage_proto_goTypes = nil
	file_mortgage_proto_depIdxs = nil
}
