syntax = "proto3";
package mortgage;

option go_package = "./pbgo/mortgagepb";

message MortgageConfig {
    repeated MortgageGroup groups = 1;
}

message MortgageGroup {
    string name = 1;
    repeated Mortgage mortgages = 2;
}

message Mortgage {
    double total = 1;
    string mortgage_first_payment = 2;
    uint32 mortgage_duration_in_years = 3;
    double interest_rate_percentage = 4;
    repeated Downpayment downpayments = 5;
    optional string mortgage_end_date = 6;
}

message Downpayment {
    string date = 1;
    double sum = 2;
}
