// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.3
// source: car.proto

package carpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CarConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cars          []*Car                 `protobuf:"bytes,1,rep,name=cars,proto3" json:"cars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarConfig) Reset() {
	*x = CarConfig{}
	mi := &file_car_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarConfig) ProtoMessage() {}

func (x *CarConfig) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarConfig.ProtoReflect.Descriptor instead.
func (*CarConfig) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{0}
}

func (x *CarConfig) GetCars() []*Car {
	if x != nil {
		return x.Cars
	}
	return nil
}

type Car struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // should be unique
	Total         float64                `protobuf:"fixed64,2,opt,name=total,proto3" json:"total,omitempty"`
	MinParfValue  float64                `protobuf:"fixed64,3,opt,name=min_parf_value,json=minParfValue,proto3" json:"min_parf_value,omitempty"`
	Lifespan      int32                  `protobuf:"varint,4,opt,name=lifespan,proto3" json:"lifespan,omitempty"`
	CarStartDate  string                 `protobuf:"bytes,5,opt,name=car_start_date,json=carStartDate,proto3" json:"car_start_date,omitempty"`
	CarSoldDate   string                 `protobuf:"bytes,6,opt,name=car_sold_date,json=carSoldDate,proto3" json:"car_sold_date,omitempty"`
	Loan          *Loan                  `protobuf:"bytes,7,opt,name=loan,proto3" json:"loan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Car) Reset() {
	*x = Car{}
	mi := &file_car_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Car) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Car) ProtoMessage() {}

func (x *Car) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Car.ProtoReflect.Descriptor instead.
func (*Car) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{1}
}

func (x *Car) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Car) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Car) GetMinParfValue() float64 {
	if x != nil {
		return x.MinParfValue
	}
	return 0
}

func (x *Car) GetLifespan() int32 {
	if x != nil {
		return x.Lifespan
	}
	return 0
}

func (x *Car) GetCarStartDate() string {
	if x != nil {
		return x.CarStartDate
	}
	return ""
}

func (x *Car) GetCarSoldDate() string {
	if x != nil {
		return x.CarSoldDate
	}
	return ""
}

func (x *Car) GetLoan() *Loan {
	if x != nil {
		return x.Loan
	}
	return nil
}

type Loan struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// interest rate is always simple interest
	Amount          float64 `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Duration        int32   `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	InterestRate    float64 `protobuf:"fixed64,3,opt,name=interest_rate,json=interestRate,proto3" json:"interest_rate,omitempty"`
	LastMonthAmount float64 `protobuf:"fixed64,4,opt,name=last_month_amount,json=lastMonthAmount,proto3" json:"last_month_amount,omitempty"` // for some reason, last month's amount is usually different.
	StartDate       string  `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Loan) Reset() {
	*x = Loan{}
	mi := &file_car_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Loan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Loan) ProtoMessage() {}

func (x *Loan) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Loan.ProtoReflect.Descriptor instead.
func (*Loan) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{2}
}

func (x *Loan) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Loan) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Loan) GetInterestRate() float64 {
	if x != nil {
		return x.InterestRate
	}
	return 0
}

func (x *Loan) GetLastMonthAmount() float64 {
	if x != nil {
		return x.LastMonthAmount
	}
	return 0
}

func (x *Loan) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

var File_car_proto protoreflect.FileDescriptor

const file_car_proto_rawDesc = "" +
	"\n" +
	"\tcar.proto\x12\x03car\")\n" +
	"\tCarConfig\x12\x1c\n" +
	"\x04cars\x18\x01 \x03(\v2\b.car.CarR\x04cars\"\xda\x01\n" +
	"\x03Car\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x01R\x05total\x12$\n" +
	"\x0emin_parf_value\x18\x03 \x01(\x01R\fminParfValue\x12\x1a\n" +
	"\blifespan\x18\x04 \x01(\x05R\blifespan\x12$\n" +
	"\x0ecar_start_date\x18\x05 \x01(\tR\fcarStartDate\x12\"\n" +
	"\rcar_sold_date\x18\x06 \x01(\tR\vcarSoldDate\x12\x1d\n" +
	"\x04loan\x18\a \x01(\v2\t.car.LoanR\x04loan\"\xaa\x01\n" +
	"\x04Loan\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x05R\bduration\x12#\n" +
	"\rinterest_rate\x18\x03 \x01(\x01R\finterestRate\x12*\n" +
	"\x11last_month_amount\x18\x04 \x01(\x01R\x0flastMonthAmount\x12\x1d\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tR\tstartDateB\x0eZ\f./pbgo/carpbb\x06proto3"

var (
	file_car_proto_rawDescOnce sync.Once
	file_car_proto_rawDescData []byte
)

func file_car_proto_rawDescGZIP() []byte {
	file_car_proto_rawDescOnce.Do(func() {
		file_car_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_car_proto_rawDesc), len(file_car_proto_rawDesc)))
	})
	return file_car_proto_rawDescData
}

var file_car_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_car_proto_goTypes = []any{
	(*CarConfig)(nil), // 0: car.CarConfig
	(*Car)(nil),       // 1: car.Car
	(*Loan)(nil),      // 2: car.Loan
}
var file_car_proto_depIdxs = []int32{
	1, // 0: car.CarConfig.cars:type_name -> car.Car
	2, // 1: car.Car.loan:type_name -> car.Loan
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_car_proto_init() }
func file_car_proto_init() {
	if File_car_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_car_proto_rawDesc), len(file_car_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_car_proto_goTypes,
		DependencyIndexes: file_car_proto_depIdxs,
		MessageInfos:      file_car_proto_msgTypes,
	}.Build()
	File_car_proto = out.File
	file_car_proto_goTypes = nil
	file_car_proto_depIdxs = nil
}
